### ISSUE TITLE
Investigate using BouncyCastle to avoid requiring libsunec shared library with GraalVM's native-image

### ISSUE THREAD

**Issue by briandealwis** [briandealwis/cram#3]
https://github.com/oracle/graal/issues/1336

**Comment by lvh** [comment]
You can just use Graal 19.3.0 now and it'll magically fix this, no BouncyCastle required.

**Comment by briandealwis** [comment]
Thanks for letting me know! Giving it a whirl now 🤞

**Comment by briandealwis** [comment]
@lvh so I still see warning messages around SunEC on startup:
```
WARNING: The sunec native library, required by the SunEC provider, could not be loaded. This library is usually shipped as part of the JDK and can be found under <JAVA_HOME>/jre/lib/<platform>/libsunec.so. It is loaded at run time via System.loadLibrary("sunec"), the first time services from SunEC are accessed. To use this provider's services the java.library.path system property needs to be set accordingly to point to a location that contains libsunec.so. Note that if java.library.path is not set it defaults to the current working directory.
```

I'm using native-image with its `--enable-all-security-services  --enable-http --enable-https` options.  Is there something further?

**Comment by lvh** [comment]
What Graal version are you using exactly? Works for me and I have a demo project (see https://www.lvh.io/posts/clojure-and-native-image-on-jdk-11-flavored-graalvm-1930%2B/) -- maybe try that and see if we can localize it to something specific with this project?

**Comment by lvh** [comment]
(Sorry, it just occurred to me that you're not a Clojure project -- that shouldn't matter but it may make it trickier for you to run my reproducer :))

**Comment by briandealwis** [comment]
@lvh it turns out I was testing the wrong generated binary :blush: — it's working fine now.  Thanks for the pointer!

**Comment by briandealwis** [comment]
Closing as no longer required.
